[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd /app/backend && npm install"]

[phases.build]
cmds = ["cd /app/backend && npm run build"]
dependsOn = ["install"]

[start]
cmd = "cd /app/backend && node dist/main.js"
